version: '3.1'

services:
  smyersnet:
    container_name: 'www-smyersnet'
    ports:
      - "2002:3000"
    build:
      context: .
      dockerfile: Dockerfile

networks:
  homedock:
    external: true
